# -*- coding: utf-8 -*-
"""Explorando_IA_Generativa.git

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q94RncuD7uxMNraoQaqltyyVZiQXAmMG
"""

openai_api_key = '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'

import pandas as pd
!pip install pandas
!pip install openai

df = pd.read_excel('Desafio.xlsx')
alunos_df = df[['NomeAluno','Recuperacao','HorarioEstudo','Dias','DiasProva']]
alunos_df = alunos_df[alunos_df['Recuperacao'].notna()]

alunos = []
alunos.append(alunos_df)
print(alunos)

import openai

openai.api_key = openai_api_key

def generate_study_schedule(alunos):
    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {
                "role": "system",
                "content": "Você é um especialista em criar cronogramas de estudos para alunos."
            },
            {
                "role": "user",
                "content": f"Crie um cronograma de estudos para {aluno['NomeAluno']} nas matérias {aluno['Recuperacao']}, dentro do horário de {aluno['HorarioEstudo']}. Saiba que faltam {aluno['DiasProva']} dias para a prova e ele só tem {aluno['Dias']} dias na semana para estudar. (Maximo 100 caracteres)"
            }
        ]
    )
    return completion.choices[0].message['content']

for aluno in alunos:
  news = generate_study_schedule(aluno)
  print(news)